name: celguard 
description: Pull Request Linter with CEL
author: konojunya
inputs:
  config:
    description: 'Path to the config file'
    required: true
    default: '.github/celguard.yaml'
  version:
    description: 'Version to use'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: download celguard
      shell: bash
      env:
        TAG:  ${{ github.action_ref }}
      run: |
        set -euo pipefail
        base="https://github.com/konojunya/celguard/releases/download/${TAG}"
        curl -LsSf "${base}/celguard_${TAG#v}_linux_amd64.tar.gz" -o "celguard_${TAG#v}_linux_amd64.tar.gz"
        curl -LsSf "${base}/checksums.txt" -o checksums.txt

        # checksum verification
        grep " celguard_${TAG#v}_linux_amd64.tar.gz" checksums.txt | sha256sum -c --status

        tar -xzf "celguard_${TAG#v}_linux_amd64.tar.gz"
        chmod +x celguard_linux_x86_64
        mv celguard_linux_x86_64 celguard
    - name: run celguard
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: ./celguard ${{ inputs.config }}

branding:
  icon: 'git-pull-request'
  color: 'white'
